

#ifndef __CONSTANTS__
#define __CONSTANTS__

int NUMBER_OF_CARGO_PLANES;
int MIN_FLOUR_CONTAINERS;
int MAX_FLOUR_CONTAINERS;
int MIN_DROP_TIME;
int MAX_DROP_TIME;
int REFILL_PERIOD_MIN;
int REFILL_PERIOD_MAX;
int COLLECTING_RELIEF_COMMITTEES;
int COLLECTING_RELIEF_WORKERS;
int SPLITTING_RELIEF_WORKERS;
int DISTRIBUTING_RELIEF_WORKERS;
int NUMBER_OF_BAGS_PER_DISTRIBUTION;
int LIMIT_DISTRIBUTE_DROP;
int THRESHOLD_TIME;
int THRESHOLD_DEATH_RATE;
int THRESHOLD_CARGO_PLANES_CRASHED;
int THRESHOLD_CONTAINERS_DOWN;
int THRESHOLD_COLLECTING_WORKERS_DOWN;
int THRESHOLD_DISTRIBUTING_WORKERS_DOWN;
int THRESHOLD_FAMILIES_DOWN;


#endif


